// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlwa_YmOATF6P9sS37I3fOKgi0H_YvfAQ',
    appId: '1:814602681884:web:303c8b608269d8cdc2e9d9',
    messagingSenderId: '814602681884',
    projectId: 'walletpadi',
    authDomain: 'walletpadi.firebaseapp.com',
    storageBucket: 'walletpadi.firebasestorage.app',
    measurementId: 'G-V9KSPCV16T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCipTD32JJDJG7met3Y7_tALCPvRyaDA5Y',
    appId: '1:814602681884:android:d759426baa632bafc2e9d9',
    messagingSenderId: '814602681884',
    projectId: 'walletpadi',
    storageBucket: 'walletpadi.firebasestorage.app',
  );
}
